<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
	<ServerGarbageCollection>false</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\**" />
    <Content Remove="Data\**" />
    <EmbeddedResource Remove="Data\**" />
    <None Remove="Data\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="efpt.config.json.user" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ixnas.AltchaNet" Version="1.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="10.0.10" />
    <PackageReference Include="NetMQ" Version="4.0.4.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\" />
    <Folder Include="wwwroot\lib\jquery-validation-unobtrusive\" />
    <Folder Include="wwwroot\lib\jquery-validation\" />
    <Folder Include="wwwroot\lib\jquery-validation\dist\" />
    <Folder Include="wwwroot\lib\jquery\" />
    <Folder Include="wwwroot\lib\jquery\dist\" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\licences\licences.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties /></VisualStudio></ProjectExtensions>

</Project>
